# configure
image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"  # cache on project level
cache:
  paths:
    - .cache/pip
    - venv/

# common to all scripts
before_script:
  - python -V
  - pip install -U virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U "flit!=3.7.0" "flit-core!=3.7.0"
  - pip install -U pytest
  - pip install -U mypy
  - pip install -U yaqc
  - pip install -U yaqd-core
  - pip install -U yaq-traits
  - pip install .

# test stage

mypy:
  stage: test
  script:
    - mypy yaqd_pmc
entry:
  stage: test
  script:
    - yaqd-pmc --version
    - yaqd-pmc -h
traits:
  stage: test
  script:
    - for i in yaqd_pmc/*.avpr; do yaq-traits check $i; done

# deploy stage
flit:
  stage: deploy
  script:
    - flit publish
  artifacts:
    paths:
      - dist/*
  only:
    - tags
